---

- hosts: web
  tasks:
  - name: Install apache2 pnd php packages for ubuntu
    apt:
      name:
        -  apache2      
        -  libapache2-mod-php
      state: latest
      update_cache: yes  
    when: ansible_distribution == "Ubuntu" 

  - name: copy default html file for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

